#!/bin/sh
#
# Pre-commit hooks

######################################################################
# Environment Setup
# 1) Change directory to build dir so we can run grunt tasks.
# 2) Make sure path is extended to include grunt task executable
#    dir, as this commit shell is executed in the git
#    client's own shell; ie Tower and WebStorm have own shell path.
######################################################################

PATH=$PATH:~/usr/local/bin
PATH=$PATH:/usr/local/bin

######################################################################
# Lint:CSS : Lint stuff before commiting
######################################################################

npm run lint:css
EXIT_CODE=$?

if [[ ${EXIT_CODE} -ne 0 ]]; then
    echo "[ERRROR] code = " ${EXIT_CODE}
    echo "Lint:CSS detected syntax problems."
    echo "Commit aborted."
    exit 1
else
	echo "Lint:CSS completed successfully\n"
fi

######################################################################
# Lint:TS : Lint stuff before commiting
######################################################################

npm run lint:ts
EXIT_CODE=$?

if [[ ${EXIT_CODE} -ne 0 ]]; then
    echo "[ERRROR] code = " ${EXIT_CODE}
    echo "Lint:TS detected syntax problems."
    echo "Commit aborted."
    exit 1
else
	echo "Lint:TS completed successfully\n"
fi

exit 0
